# Generated by Django 5.0.7 on 2024-07-24 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Ім'я та фамілія")),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер телефону')),
                ('task', models.IntegerField(choices=[(0, 'Ландшафтний дизайн'), (1, 'Клінінг'), (2, "Облаштування інтер'єру"), (3, 'Охоронна система'), (4, "Дизайн інтер'єру")])),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
